### ISSUE TITLE
Backend unit testing

### ISSUE THREAD

**Issue by nfischer** [nfischer/course-dashboard#12]
I think we should set up unit testing for the flask stuff. The sooner the better, since we're required to have it done anyway.

Reasons to do it sooner:
- Continuous Integration: This will run all our unit tests on every push and pull request, so that makes sure that we never merge broken code (which is tough to resolve later on).
- Peer review: This goes along with the CI stuff. Once we have continuous integration, this will significantly cut down on the peer review time for pull requests, which will help speed up our process later on, which is when development pace will be critical.
- We have to have tests eventually, and it's better to find out sooner rather than later if our testing framework won't work for us.

**Comment by nfischer** [comment]
Any update on this?

**Comment by rtcothern** [comment]
Herman had picked this up

**Comment by nfischer** [comment]
@Sarabostani please switch over to developing tests on the `backend-testing` branch. It is up to date with the last version of `backend` pushed. I will be using `backend` for new development.

**Comment by nfischer** [comment]
This is (mostly) resolved in #36
