### ISSUE TITLE
Title-less resources are unclickable

### ISSUE THREAD

**Issue by nfischer** [nfischer/course-dashboard#15]
Creating a resource without a title makes it not appear (can't click on it since it isn't in the UI). This probably isn't what we want. Either a javascript alert which reminds the user to make a title, or perhaps the "title" is a snippet of the body of the resource (i.e. "Hey guys, check out this really cool website I found the other day." could have the "title" "Hey guys, check out..." and the body will still be the full text).

**Comment by sakekasi** [comment]
Issue resolved in [pull request 16](https://github.com/nfischer/course-dashboard/pull/16)
