### ISSUE TITLE
allow users to edit and delete their own resources

### ISSUE THREAD

**Issue by sakekasi** [nfischer/course-dashboard#18]
I would probably do this by associating the user id and resource markdown with the content and modifying the resource renderer to only render the markdown.

**Comment by nfischer** [comment]
What does this need in backend? Does this need to associate a user with a list of resources they've uploaded?

**Comment by sakekasi** [comment]
This wouldn't need anything in backend other than what's already implemented. frontend would just keep track of which users made what to render ui to delete, then call the usual ops

**Comment by nfischer** [comment]
But isn't the backend necessary for persistent state? Otherwise, how will we know which resources `user x` uploaded last week?

And actually, a better implementation is to have an `author` field in the node object, so it would be a simple change to the node database (but would change our node API).

**Comment by sakekasi** [comment]
We don't have to worry about that while implementing. basically, serialize an arbitrary json object and put it in contents to persist it.

**Comment by nfischer** [comment]
So you're saying that the `contents` field would contain extra info, such as `author`?

**Comment by sakekasi** [comment]
yup

**Comment by nfischer** [comment]
This is mostly implemented (the resource editing and deletion work, but we don't have the notion of a user at this point). Closing this issue (can be reopened if adding in users doesn't fix the problem completely)
