### ISSUE TITLE
Have frontend/index.html served at the endpoint /<course_id>/ 

### ISSUE THREAD

**Issue by sakekasi** [nfischer/course-dashboard#23]
This would be useful for the frontend, as through this, we could parametrize the frontend by class.

**Comment by nfischer** [comment]
The concern then is, how will users switch between classes? We should have a menu somewhere (like how Piazza does it) that would make it easy to switch from one course to another.

**Comment by sakekasi** [comment]
I think something as simple as an index menu that just listed classes would be good for now

**Comment by nfischer** [comment]
So what would that look like? Would that be a page that loads first, and then prompts the user to choose which course to go to (which redirects to another page)?

**Comment by sakekasi** [comment]
yeah. Could be that simple. The frontend would parse its url to figure out what courseId should be

**Comment by nfischer** [comment]
So it sounds like we'll need a menu page first from Frontend, and then change our project to start serving at that file. What else will we need to do to get this working?

**Comment by sakekasi** [comment]
I would focus on serving static/index.html at any url /<course_id> . From there, we can use flask templates, or some kind of frontend focused method to serve a simple list of available courses. doesn't need to be anything fancy, as it wasn't part of our committed features

**Comment by nfischer** [comment]
Resolved in #26
