### ISSUE TITLE
take down or update posterator

### ISSUE THREAD

**Issue by sakekasi** [nfischer/course-dashboard#25]

**Comment by nfischer** [comment]
I'll take a look at this later today and see if it's worth it to update posterator. At this point, even fixing what functionality it used to have would be so limited, I'm inclined to just tell people to use:

``` Python
$ python
>>> from addSampleData import *
>>> add_node(contents='foo', renderer='bar').json() # will print results
>>> delete_node(1).json()
>>> # etc.
```

**Comment by sakekasi** [comment]
I have no problem with that

**Comment by sakekasi** [comment]
Fixed in https://github.com/nfischer/course-dashboard/pull/26
