### ISSUE TITLE
Fix rendering bug where contents of a modal dialog do not rerender until they are closed

### ISSUE THREAD

**Issue by sakekasi** [nfischer/course-dashboard#6]

**Comment by sakekasi** [comment]
Resolved the issue. since ReduceStores use === to check if they should emit an event, mutating state by reference leads to unusual behaviour. I would like to find a way to make these states actually immutable rather than just pretending they are in the future.

**Comment by sakekasi** [comment]
Resolved the issue. since ReduceStores use === to check if they should emit an event, mutating state by reference leads to unusual behaviour. I would like to find a way to make these states actually immutable rather than just pretending they are in the future.

**Comment by nfischer** [comment]
Which PR fixes this? I think we should leave this open until the PR is merged (and then comment which PR fixes it, so that everyone knows it's been fixed)

**Comment by sakekasi** [comment]
fixed in [pull request 14](https://github.com/nfischer/course-dashboard/pull/14)
