### ISSUE TITLE
Clean up UI, change fonts in use, and make better use of visual space

### ISSUE THREAD

**Issue by sakekasi** [nfischer/course-dashboard#7]
fira sans is a reasonable choice to try for font

**Comment by sakekasi** [comment]
for the visual space, dimensions should be determined based on the dimensions of the screen

**Comment by nfischer** [comment]
Also, let's consider adding in colors to distinguish different node types. This would be useful for distinguishing between announcements/assignments/resources.

**Comment by sakekasi** [comment]
Good idea. I implemented the beginnings of this in the latest pull request if you wanna take a look

**Comment by sakekasi** [comment]
[bariol](http://bariol.com/booklet/) with some rounded corners would make for a pretty friendly UI

**Comment by sakekasi** [comment]
some simple animations would help too

**Comment by sakekasi** [comment]
*friendly, but professional

**Comment by nfischer** [comment]
I think it's safe to say that this has been addressed by now.
