### ISSUE TITLE
Update resources upon creation

### ISSUE THREAD

**Issue by nfischer** [nfischer/course-dashboard#9]
When we add a resource, as soon as we click "create," it should be visible in the list of resources. Right now, we have to close and reopen the list of resources under the topic in order to see the update.

**Comment by nfischer** [comment]
Which PR closed this? Could you comment the PR number, just so we have it on record here as well? Once that PR is merged, we can close this issue.

**Comment by nfischer** [comment]
Looks like PR #14 is the one that fixes this. Will close this issue once it's merged

**Comment by sakekasi** [comment]
fixed in [pull request 14](https://github.com/nfischer/course-dashboard/pull/14)
